language: node_js
node_js:
  - '6'
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install selenium-webdriver@^3.0.0
  - npm install
script:
  - npm run test
